-- RepoLens v2.1 authoritative MySQL schema. Runtime does not use GORM
-- AutoMigrate; this file is applied by internal/platform/mysql.

CREATE TABLE IF NOT EXISTS repositories (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    name VARCHAR(128) NOT NULL,
    git_url VARCHAR(512) NOT NULL,
    default_ref VARCHAR(128) NOT NULL DEFAULT 'main',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_repository_git_url (git_url),
    KEY idx_repo_user_status_created (user_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS repository_snapshots (
    id VARCHAR(64) PRIMARY KEY,
    repository_id VARCHAR(64) NOT NULL,
    commit_sha VARCHAR(64) NOT NULL,
    ref VARCHAR(128) NOT NULL,
    requested_ref VARCHAR(128) NULL,
    materialized_path VARCHAR(512) NOT NULL,
    content_hash VARCHAR(64) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    file_count INT NOT NULL DEFAULT 0,
    total_bytes BIGINT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ready_at DATETIME(3) NULL,
    UNIQUE KEY uq_snapshot_repo_commit (repository_id, commit_sha),
    KEY idx_snapshot_repo_status_created (repository_id, status, created_at),
    CONSTRAINT chk_snapshot_status CHECK (status IN ('CREATED', 'MATERIALIZING', 'READY', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS code_index_builds (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    snapshot_id VARCHAR(64) NOT NULL,
    parser_version VARCHAR(32) NOT NULL,
    analyzer_version VARCHAR(32) NOT NULL,
    symbol_schema_version VARCHAR(32) NOT NULL,
    build_context_hash VARCHAR(64) NOT NULL,
    module_path VARCHAR(255) NOT NULL,
    goos VARCHAR(32) NOT NULL DEFAULT 'linux',
    goarch VARCHAR(32) NOT NULL DEFAULT 'amd64',
    build_tags_hash VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    files_total INT NOT NULL DEFAULT 0,
    files_parsed INT NOT NULL DEFAULT 0,
    files_failed INT NOT NULL DEFAULT 0,
    packages_total INT NOT NULL DEFAULT 0,
    packages_typechecked INT NOT NULL DEFAULT 0,
    packages_failed INT NOT NULL DEFAULT 0,
    symbol_count INT NOT NULL DEFAULT 0,
    semantic_relation_count INT NOT NULL DEFAULT 0,
    syntactic_relation_count INT NOT NULL DEFAULT 0,
    heuristic_relation_count INT NOT NULL DEFAULT 0,
    unresolved_relation_count INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ready_at DATETIME(3) NULL,
    UNIQUE KEY uq_code_index_identity (snapshot_id, parser_version, analyzer_version, symbol_schema_version, build_context_hash),
    KEY idx_cib_snapshot_status (snapshot_id, status),
    CONSTRAINT chk_code_index_build_status CHECK (status IN ('CREATED', 'BUILDING', 'READY', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS code_files (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    code_index_build_id BIGINT NOT NULL,
    path VARCHAR(512) NOT NULL,
    package_path VARCHAR(255) NOT NULL,
    package_name VARCHAR(128) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    line_count INT NOT NULL DEFAULT 0,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    is_test BOOLEAN NOT NULL DEFAULT FALSE,
    included_by_build_context BOOLEAN NOT NULL DEFAULT TRUE,
    parse_status VARCHAR(32) NOT NULL DEFAULT 'OK',
    parse_error TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_file_build_path (code_index_build_id, path)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS symbols (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    code_index_build_id BIGINT NOT NULL,
    file_id BIGINT NOT NULL,
    file_path VARCHAR(512) NOT NULL,
    symbol_key_raw VARCHAR(512) NOT NULL,
    symbol_key_hash VARCHAR(64) NOT NULL,
    module_path VARCHAR(255) NOT NULL,
    package_path VARCHAR(255) NOT NULL,
    package_name VARCHAR(128) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    name VARCHAR(128) NOT NULL,
    qualified_name VARCHAR(255) NOT NULL,
    receiver_raw VARCHAR(128) NULL,
    receiver_canonical VARCHAR(128) NULL,
    signature TEXT NULL,
    doc TEXT NULL,
    start_line INT NOT NULL,
    start_col INT NOT NULL,
    end_line INT NOT NULL,
    end_col INT NOT NULL,
    exported BOOLEAN NOT NULL DEFAULT FALSE,
    content_hash VARCHAR(64) NOT NULL,
    KEY idx_symbol_build_hash (code_index_build_id, symbol_key_hash),
    KEY idx_symbol_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS symbol_relations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    code_index_build_id BIGINT NOT NULL,
    from_symbol_id BIGINT NULL,
    from_symbol_key_hash VARCHAR(64) NULL,
    to_symbol_id BIGINT NULL,
    to_symbol_key_hash VARCHAR(64) NULL,
    relation_type VARCHAR(32) NOT NULL,
    resolution_kind VARCHAR(32) NOT NULL,
    confidence DOUBLE NOT NULL DEFAULT 1.0,
    reason_code VARCHAR(64) NOT NULL,
    reason_detail VARCHAR(255) NULL,
    target_name VARCHAR(128) NULL,
    target_package_path VARCHAR(255) NULL,
    target_qualified_name VARCHAR(255) NULL,
    file_path VARCHAR(512) NOT NULL,
    file_id BIGINT NOT NULL,
    line INT NOT NULL,
    `column` INT NOT NULL,
    KEY idx_relation_build (code_index_build_id),
    KEY idx_relation_from (from_symbol_id),
    KEY idx_relation_to (to_symbol_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS retrieval_builds (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    code_index_build_id BIGINT NOT NULL,
    strategy VARCHAR(32) NOT NULL,
    retrieval_version VARCHAR(32) NOT NULL,
    tokenizer_version VARCHAR(32) NOT NULL,
    config_hash VARCHAR(64) NOT NULL,
    artifact_path VARCHAR(512) NOT NULL DEFAULT '',
    artifact_hash VARCHAR(64) NOT NULL DEFAULT '',
    document_count INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    error_code VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ready_at DATETIME(3) NULL,
    UNIQUE KEY uq_retrieval_identity (code_index_build_id, strategy, retrieval_version, tokenizer_version, config_hash),
    KEY idx_retrieval_cib_status (code_index_build_id, status),
    CONSTRAINT chk_retrieval_build_status CHECK (status IN ('CREATED', 'BUILDING', 'READY', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS analysis_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    job_type VARCHAR(64) NOT NULL,
    resource_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    execution_generation INT NOT NULL DEFAULT 1,
    terminal_reason VARCHAR(32) NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    next_run_at DATETIME(3) NOT NULL,
    worker_id VARCHAR(64) NULL,
    claim_token VARCHAR(64) NULL,
    lease_until DATETIME(3) NULL,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    last_error_class VARCHAR(32) NULL,
    last_error_code VARCHAR(64) NULL,
    last_error_message TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    finished_at DATETIME(3) NULL,
    UNIQUE KEY uq_job_resource (job_type, resource_id),
    KEY idx_job_claim (status, next_run_at, created_at),
    KEY idx_job_lease (status, lease_until),
    CONSTRAINT chk_analysis_job_status CHECK (status IN ('PENDING', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS diagnosis_runs (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL,
    repository_id VARCHAR(36) NOT NULL,
    snapshot_id VARCHAR(64) NOT NULL,
    code_index_build_id BIGINT NOT NULL DEFAULT 0,
    retrieval_build_id BIGINT NOT NULL DEFAULT 0,
    issue_title VARCHAR(255) NOT NULL,
    issue_description TEXT NULL,
    error_log MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    provider_endpoint_fingerprint VARCHAR(64) NOT NULL DEFAULT '',
    provider_config_fingerprint VARCHAR(64) NOT NULL DEFAULT '',
    normalized_base_url VARCHAR(512) NOT NULL DEFAULT '',
    model_name VARCHAR(128) NOT NULL DEFAULT '',
    prompt_version VARCHAR(64) NOT NULL DEFAULT '',
    agent_version VARCHAR(64) NOT NULL DEFAULT '',
    agent_config_hash VARCHAR(64) NOT NULL DEFAULT '',
    temperature DOUBLE NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(128) NOT NULL,
    idempotency_request_hash VARCHAR(64) NOT NULL,
    final_attempt_id VARCHAR(36) NULL,
    version INT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_diagnosis_idempotency (user_id, idempotency_key),
    KEY idx_diagnosis_lineage (snapshot_id, code_index_build_id, retrieval_build_id),
    KEY idx_diagnosis_status_created (status, created_at),
    CONSTRAINT chk_diagnosis_status CHECK (status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS diagnosis_attempts (
    id VARCHAR(36) PRIMARY KEY,
    diagnosis_run_id VARCHAR(36) NOT NULL,
    attempt_no INT NOT NULL,
    worker_id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    started_at DATETIME(3) NOT NULL,
    heartbeat_at DATETIME(3) NOT NULL,
    deadline_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    error_code VARCHAR(64) NULL,
    error_message TEXT NULL,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    model VARCHAR(64) NULL,
    prompt_tokens INT NOT NULL DEFAULT 0,
    completion_tokens INT NOT NULL DEFAULT 0,
    tool_calls INT NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    KEY idx_attempt_run_no (diagnosis_run_id, attempt_no),
    KEY idx_attempt_status_heartbeat (status, heartbeat_at),
    CONSTRAINT chk_attempt_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED_RETRYABLE', 'FAILED_TERMINAL', 'CANCELLED', 'ABANDONED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reports (
    id VARCHAR(36) PRIMARY KEY,
    diagnosis_run_id VARCHAR(36) NOT NULL,
    attempt_id VARCHAR(36) NOT NULL,
    root_cause TEXT NOT NULL,
    findings_json TEXT NOT NULL,
    recommended_checks_json TEXT NULL,
    confidence DOUBLE NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_report_run (diagnosis_run_id),
    KEY idx_report_attempt (attempt_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS citations (
    id VARCHAR(36) PRIMARY KEY,
    report_id VARCHAR(36) NULL,
    snapshot_id VARCHAR(64) NOT NULL,
    code_index_build_id BIGINT NOT NULL DEFAULT 0,
    file_path VARCHAR(512) NOT NULL,
    start_line INT NOT NULL,
    end_line INT NOT NULL,
    excerpt TEXT NULL,
    reason VARCHAR(255) NULL,
    content_hash VARCHAR(64) NULL,
    validation_status VARCHAR(32) NOT NULL DEFAULT 'UNCHECKED',
    validation_error VARCHAR(255) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    KEY idx_citation_report (report_id),
    KEY idx_citation_lineage (snapshot_id, code_index_build_id),
    CONSTRAINT chk_citation_status CHECK (validation_status IN ('VALID', 'INVALID', 'UNCHECKED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_steps (
    id VARCHAR(36) PRIMARY KEY,
    attempt_id VARCHAR(36) NOT NULL,
    seq INT NOT NULL,
    step_type VARCHAR(32) NOT NULL,
    tool_name VARCHAR(64) NULL,
    tool_args_summary TEXT NULL,
    tool_result_summary MEDIUMTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'COMPLETED',
    latency_ms BIGINT NOT NULL DEFAULT 0,
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    UNIQUE KEY uq_step_attempt_seq (attempt_id, seq)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
